name: Medusa
version: 1.5.3
main: ai.medusa.anticheat.MedusaPlugin
authors: [infinitesm]
description: Medusa Anticheat

commands:
  medusa:
    description: Commands for Medusa Anticheat.
    usage: /medusa
    aliases: [anticheat, ac]
    permission: medusa.commands


